# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Home
description: Melih Gültekin
keywords: "android, kotlin, java, flutter"
skills: "Android Developer - Software Engineer - Freelancer"

author:
  name: Melih Gültekin
  welcome: Hello there! 👋 I'm Melih Gültekin. Welcome to my page!
  about: >- # this means to ignore newlines until "baseurl:"
    Android Geek since 2014, Software Engineer, Programmer, Clean Code follower, Open Source lover 😌
  social: Around the Web

# Social networks usernames
social:
  - title: linkedin
    url: https://www.linkedin.com/in/melih-g%C3%BCltekin-a2a41464/
  - title: github
    url: http://github.com/melomg
  - title: twitter
    url: https://twitter.com/melihgultekin
  - title: medium
    url: https://medium.com/@mmelihgultekin
  - title: stack-overflow
    url: https://stackoverflow.com/users/3918109/melomg

# Footer settings
footer:
  copyright: Melih Gültekin
  location: Location
  credits: Credits

# Postal address (add as many lines as necessary)
address:
  - line: Randstad Area, The Netherlands

# Credits content
credits: 'This website is built on top the <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer Theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fff #18bc9c #80B3FF
  onPrimary: 000000 #80B3FF
  outline: 000000 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondaryDark: 233140 #A2122F
  tertiary: 18bc9c #18bc9c #80B3FF
