# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.markdown, Capfile, bin, s3_website.yml, tmp]
paginate: 5
paginate_path: /page:num/
plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed
remote_theme: "mmistakes/so-simple-theme@3.2.0"
#theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
masthead_title: Home

title: "Melih Gültekin"
description: "Android Developer - Software Engineer - Freelancer"
keywords: "android, kotlin, java, engineer"
logo: "/assets/images/profile.jpeg"
masthead_bio: "Android Geek since 2014, Software Engineer, Programmer, Clean Code and Open Source follower..."
twitter:
  username: melihgultekin

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 150

search: true

author:
  location: "Randstad Area, The Netherlands"
  picture: /assets/images/profile.jpeg
  bio: "Android Geek since 2014, Software Engineer, Programmer, Clean Code follower, Open Source lover 😌"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/melih-g%C3%BCltekin-a2a41464/"
    - label: "github"
      icon: "fab fa-fw fa-github-square"
      url: "http://github.com/melomg"

# Social networks usernames
social:
  - title: linkedin
    url: https://www.linkedin.com/in/melih-g%C3%BCltekin-a2a41464/
  - title: github
    url: http://github.com/melomg
  - title: twitter
    url: https://twitter.com/melihgultekin
  - title: medium
    url: https://medium.com/@mmelihgultekin
  - title: stack-overflow
    url: https://stackoverflow.com/users/3918109/melomg

# Footer settings
footer:
  copyright: Melih Gültekin
  location: Location
  credits: Credits

# Postal address (add as many lines as necessary)
address:
  - line: Randstad Area, The Netherlands

footer_links:
  - title: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/melih-g%C3%BCltekin-a2a41464/"
  - title: "github"
    icon: "fab fa-fw fa-github-square"
    url: "http://github.com/melomg"
  - title: "medium"
    icon: "fab fa-fw fa-medium"
    url: "https://medium.com/@mmelihgultekin"
  - title: "stack-overflow"
    icon: "fab fa-fw fa-stack-overflow"
    url: "https://stackoverflow.com/users/3918109/melomg"
  - title: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/melihgultekin"

url: "https://melihgultekin.dev/"
feed:
  path: feed.xml

defaults:
  # _posts
  defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

locale: en-US

# Credits content
credits: 'This website is built on top the <a href="https://github.com/mmistakes/so-simple-theme" target="_blank">So Simple Theme</a>.'
copyright: Melih Gültekin

google_fonts:
  - name: "Enriqueta"
    weights: "400,500,600,700"
  - name: "Lora"
    weights: "400,400i,700,700i"
